---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - /bin/sh
          - -c
          - |-
            touch /busybox-log
            tail -f /busybox-log
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |-
                echo $POD_IP >> /busybox-log
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |-
                echo $POD_NAMESPACE >> /busybox-log

