apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: ynet-uptime
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ynet-uptime
            image: busybox
            args:
            - /bin/sh
            - -c
            - wget http://www.ynet.co.il -O/dev/null
          restartPolicy: Never

