---
apiVersion: v1
kind: Pod
metadata:
  name: wp
  labels:
    app: wp
spec:
  containers:
  - image: wordpress
    env:
    - name: WORDPRESS_DB_PASSWORD
      value: admin
    - name: WORDPRESS_DB_USER
      value: admin
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_NAME
      value: wordpress
    imagePullPolicy: IfNotPresent
    name: wordpress
  - image: mysql:5.5
    env:
    - name: MYSQL_USER
      value: admin
    - name: MYSQL_PASSWORD
      value: admin
    - name: MYSQL_ROOT_PASSWORD
      value: admin
    - name: MYSQL_DATABASE
      value: wordpress
    imagePullPolicy: IfNotPresent
    name: mysql
  restartPolicy: Always

# Solution to the "advanced" question:
# kubectl port-forward wp 8001:80

